-- One-time fix for entities switched from GenerationType.SEQUENCE to IDENTITY.
-- ddl-auto=update does NOT convert existing PK columns to identity, so Hibernate
-- sends NULL and Postgres rejects it. This script converts each PK in place and
-- seeds its identity sequence past the current MAX(id) so existing rows survive.
--
-- Run once against the impact database, e.g.:
--   psql -h localhost -p 5433 -U postgres -d impact -f fix-identity-columns.sql

BEGIN;

ALTER TABLE campaign       ALTER COLUMN campaign_id   ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "user"         ALTER COLUMN user_id       ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE college        ALTER COLUMN college_id    ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE category       ALTER COLUMN category_id   ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE application    ALTER COLUMN id            ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE attendance     ALTER COLUMN attendance_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE progress       ALTER COLUMN progress_id   ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE campaign_photo ALTER COLUMN photo_id      ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('campaign',       'campaign_id'),   COALESCE((SELECT MAX(campaign_id)   FROM campaign),       0) + 1, false);
SELECT setval(pg_get_serial_sequence('"user"',         'user_id'),       COALESCE((SELECT MAX(user_id)       FROM "user"),         0) + 1, false);
SELECT setval(pg_get_serial_sequence('college',        'college_id'),    COALESCE((SELECT MAX(college_id)    FROM college),        0) + 1, false);
SELECT setval(pg_get_serial_sequence('category',       'category_id'),   COALESCE((SELECT MAX(category_id)   FROM category),       0) + 1, false);
SELECT setval(pg_get_serial_sequence('application',    'id'),            COALESCE((SELECT MAX(id)            FROM application),    0) + 1, false);
SELECT setval(pg_get_serial_sequence('attendance',     'attendance_id'), COALESCE((SELECT MAX(attendance_id) FROM attendance),     0) + 1, false);
SELECT setval(pg_get_serial_sequence('progress',       'progress_id'),   COALESCE((SELECT MAX(progress_id)   FROM progress),       0) + 1, false);
SELECT setval(pg_get_serial_sequence('campaign_photo', 'photo_id'),      COALESCE((SELECT MAX(photo_id)      FROM campaign_photo), 0) + 1, false);

COMMIT;