-- ============================================================================
-- IMPACT FULL SEED (Railway-ready, IDENTITY-friendly)
-- Paste this whole script into Railway Data console and Run.
-- Safe to re-run: truncates app tables first.
-- ============================================================================
BEGIN;

TRUNCATE TABLE campaign_photo, attendance, application, progress, campaign, "user", category, college RESTART IDENTITY CASCADE;

-- 1) COLLEGES (6)
INSERT INTO college (name, description, created_at, updated_at) VALUES
('College of Engineering', 'Engineering and applied sciences.', NOW(), NOW()),
('College of Business',    'Business administration and economics.', NOW(), NOW()),
('College of Arts',        'Humanities, arts, and social sciences.', NOW(), NOW()),
('College of Science',     'Natural sciences and mathematics.', NOW(), NOW()),
('College of Medicine',    'Medical sciences and nursing.', NOW(), NOW()),
('College of Law',         'Law and legal studies.', NOW(), NOW());

-- 2) CATEGORIES (8)
INSERT INTO category (name, created_at, updated_at) VALUES
('Environment',     NOW(), NOW()),
('Education',       NOW(), NOW()),
('Health',          NOW(), NOW()),
('Community',       NOW(), NOW()),
('Technology',      NOW(), NOW()),
('Arts & Culture',  NOW(), NOW()),
('Sports',          NOW(), NOW()),
('Animal Welfare',  NOW(), NOW());

-- 3) USERS / STUDENTS (30 — 5 per college)
INSERT INTO "user" (student_number, first_name, last_name, email, phone, academic_year, is_banned, created_at, updated_at, college_id) VALUES
-- Engineering
('STU1001', 'Aisha',   'Rahman',   'aisha.rahman@uni.edu',   '0100000001', 2, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Engineering')),
('STU1002', 'Yousef',  'Nabil',    'yousef.nabil@uni.edu',   '0100000002', 4, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Engineering')),
('STU1003', 'Hana',    'Sami',     'hana.sami@uni.edu',      '0100000003', 1, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Engineering')),
('STU1004', 'Karim',   'Salah',    'karim.salah@uni.edu',    '0100000004', 3, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Engineering')),
('STU1005', 'Noor',    'Fawzy',    'noor.fawzy@uni.edu',     '0100000005', 2, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Engineering')),
-- Business
('STU1006', 'Omar',    'Hassan',   'omar.hassan@uni.edu',    '0100000006', 3, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Business')),
('STU1007', 'Mariam',  'Adel',     'mariam.adel@uni.edu',    '0100000007', 2, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Business')),
('STU1008', 'Tarek',   'Mostafa',  'tarek.mostafa@uni.edu',  '0100000008', 4, true,  NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Business')),
('STU1009', 'Rana',    'Ehab',     'rana.ehab@uni.edu',      '0100000009', 1, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Business')),
('STU1010', 'Sami',    'Talaat',   'sami.talaat@uni.edu',    '0100000010', 3, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Business')),
-- Arts
('STU1011', 'Lina',    'Khaled',   'lina.khaled@uni.edu',    '0100000011', 1, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Arts')),
('STU1012', 'Ziad',    'Helmy',    'ziad.helmy@uni.edu',     '0100000012', 2, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Arts')),
('STU1013', 'Nada',    'Magdy',    'nada.magdy@uni.edu',     '0100000013', 4, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Arts')),
('STU1014', 'Khaled',  'Reda',     'khaled.reda@uni.edu',    '0100000014', 3, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Arts')),
('STU1015', 'Salma',   'Wagdy',    'salma.wagdy@uni.edu',    '0100000015', 2, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Arts')),
-- Science
('STU1016', 'Hussein', 'Ali',      'hussein.ali@uni.edu',    '0100000016', 1, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Science')),
('STU1017', 'Dina',    'Younis',   'dina.younis@uni.edu',    '0100000017', 3, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Science')),
('STU1018', 'Mostafa', 'Gad',      'mostafa.gad@uni.edu',    '0100000018', 4, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Science')),
('STU1019', 'Reem',    'Ashraf',   'reem.ashraf@uni.edu',    '0100000019', 2, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Science')),
('STU1020', 'Fady',    'Naguib',   'fady.naguib@uni.edu',    '0100000020', 1, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Science')),
-- Medicine
('STU1021', 'Mai',     'Sherif',   'mai.sherif@uni.edu',     '0100000021', 2, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Medicine')),
('STU1022', 'Ahmed',   'Lotfy',    'ahmed.lotfy@uni.edu',    '0100000022', 5, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Medicine')),
('STU1023', 'Sara',    'Mansour',  'sara.mansour@uni.edu',   '0100000023', 4, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Medicine')),
('STU1024', 'Marwan',  'Fathy',    'marwan.fathy@uni.edu',   '0100000024', 1, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Medicine')),
('STU1025', 'Hala',    'Anwar',    'hala.anwar@uni.edu',     '0100000025', 6, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Medicine')),
-- Law
('STU1026', 'Bassem',  'Kamal',    'bassem.kamal@uni.edu',   '0100000026', 3, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Law')),
('STU1027', 'Heba',    'Saad',     'heba.saad@uni.edu',      '0100000027', 2, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Law')),
('STU1028', 'Yara',    'Galal',    'yara.galal@uni.edu',     '0100000028', 1, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Law')),
('STU1029', 'Tamer',   'Rifaat',   'tamer.rifaat@uni.edu',   '0100000029', 4, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Law')),
('STU1030', 'Habiba',  'Imam',     'habiba.imam@uni.edu',    '0100000030', 3, false, NOW(), NOW(), (SELECT college_id FROM college WHERE name = 'College of Law'));

-- 4) CAMPAIGNS (15) — mix of statuses
INSERT INTO campaign (title, description, location, start_date, end_date, max_volunteers, status, published_at, created_at, updated_at, proposed_by_id, approved_by_id, managed_by_id, category_id) VALUES
('Green Campus Cleanup',         'Student-led cleanup and recycling drive.',           'Main Campus',          CURRENT_DATE - 10, CURRENT_DATE + 20, 50, 'ONGOING',   NOW() - INTERVAL '9 day',  NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu'),  (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'),  (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu'), (SELECT category_id FROM category WHERE name='Environment')),
('Weekend Math Tutoring',        'Volunteers teach school students core math skills.', 'City Learning Center', CURRENT_DATE - 15, CURRENT_DATE + 30, 35, 'ONGOING',   NOW() - INTERVAL '14 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu'),    (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'),  (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu'),  (SELECT category_id FROM category WHERE name='Education')),
('Blood Donation Drive',         'Donor registration and hospital support.',           'University Hospital',  CURRENT_DATE - 40, CURRENT_DATE - 5,  80, 'COMPLETED', NOW() - INTERVAL '39 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'),    (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu'),  (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu'), (SELECT category_id FROM category WHERE name='Health')),
('Neighborhood Food Bank',       'Sort, package, and distribute food parcels.',        'Downtown Food Bank',   CURRENT_DATE - 7,  CURRENT_DATE + 25, 60, 'ONGOING',   NOW() - INTERVAL '6 day',  NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu'),   (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu'),  (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu'),  (SELECT category_id FROM category WHERE name='Community')),
('Senior Digital Literacy',      'Teach seniors smartphones and online services.',     'Community Tech Hub',   CURRENT_DATE + 5,  CURRENT_DATE + 35, 25, 'APPROVED',  NOW() - INTERVAL '2 day',  NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu'),    (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu'), (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'),  (SELECT category_id FROM category WHERE name='Technology')),
('Coastal Cleanup',              'Beach trash collection and marine awareness.',        'North Beach',          CURRENT_DATE - 3,  CURRENT_DATE + 14, 70, 'ONGOING',   NOW() - INTERVAL '4 day',  NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='hana.sami@uni.edu'),       (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'),  (SELECT user_id FROM "user" WHERE email='karim.salah@uni.edu'),  (SELECT category_id FROM category WHERE name='Environment')),
('Children Reading Hour',        'Reading sessions at the public library.',            'Central Library',      CURRENT_DATE + 10, CURRENT_DATE + 40, 20, 'APPROVED',  NOW() - INTERVAL '1 day',  NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='nada.magdy@uni.edu'),      (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'),  (SELECT user_id FROM "user" WHERE email='ziad.helmy@uni.edu'),   (SELECT category_id FROM category WHERE name='Education')),
('Hospital Visits Program',      'Bring company and games to long-stay patients.',     'University Hospital',  CURRENT_DATE - 60, CURRENT_DATE - 30, 40, 'COMPLETED', NOW() - INTERVAL '59 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='mai.sherif@uni.edu'),      (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu'),  (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu'),  (SELECT category_id FROM category WHERE name='Health')),
('Animal Shelter Volunteer Day', 'Care, walk, and groom shelter animals.',             'City Animal Shelter',  CURRENT_DATE + 7,  CURRENT_DATE + 14, 30, 'APPROVED',  NOW() - INTERVAL '3 day',  NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='salma.wagdy@uni.edu'),     (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'),  (SELECT user_id FROM "user" WHERE email='dina.younis@uni.edu'),  (SELECT category_id FROM category WHERE name='Animal Welfare')),
('University Hackathon Helpers', 'Run logistics for the 48-hour student hackathon.',   'Engineering Building', CURRENT_DATE + 14, CURRENT_DATE + 17, 45, 'PENDING',   NULL,                       NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='karim.salah@uni.edu'),     NULL,                                                            NULL,                                                            (SELECT category_id FROM category WHERE name='Technology')),
('Football Coaching Camp',       'Coach youth football basics and teamwork.',           'University Stadium',   CURRENT_DATE + 20, CURRENT_DATE + 30, 25, 'PENDING',   NULL,                       NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='tamer.rifaat@uni.edu'),    NULL,                                                            NULL,                                                            (SELECT category_id FROM category WHERE name='Sports')),
('Recycling Awareness Booth',    'Awareness booth at university fair.',                 'University Plaza',     CURRENT_DATE - 90, CURRENT_DATE - 88, 15, 'REJECTED',  NULL,                       NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='reem.ashraf@uni.edu'),     (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'),  NULL,                                                            (SELECT category_id FROM category WHERE name='Environment')),
('Refugee Language Help',        'Beginner Arabic & English for newcomers.',           'Community Hall',       CURRENT_DATE - 80, CURRENT_DATE - 70, 30, 'REJECTED',  NULL,                       NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='heba.saad@uni.edu'),       (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'),  NULL,                                                            (SELECT category_id FROM category WHERE name='Education')),
('Tree Planting Day',            'Plant 500 trees in the city park.',                  'City Park',            CURRENT_DATE - 5,  CURRENT_DATE - 1,  100,'COMPLETED', NOW() - INTERVAL '8 day',  NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='noor.fawzy@uni.edu'),      (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu'),  (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu'),  (SELECT category_id FROM category WHERE name='Environment')),
('Music for Kids',               'Performances at children hospitals.',                'Pediatric Hospital',   CURRENT_DATE + 1,  CURRENT_DATE + 12, 18, 'CANCELED',  NOW() - INTERVAL '5 day',  NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='ziad.helmy@uni.edu'),      (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu'),  NULL,                                                            (SELECT category_id FROM category WHERE name='Arts & Culture'));

-- 5) PROGRESS UPDATES (one per ONGOING/COMPLETED campaign)
INSERT INTO progress (percentage, notes, created_at, updated_at, campaign_id, updated_by_id) VALUES
(35,  'Cleanup teams assigned, phase 1 complete.',     NOW(), NOW(), (SELECT campaign_id FROM campaign WHERE title='Green Campus Cleanup'),         (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu')),
(20,  'Tutor onboarding done, schedule published.',    NOW(), NOW(), (SELECT campaign_id FROM campaign WHERE title='Weekend Math Tutoring'),        (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu')),
(100, 'Blood drive completed with strong turnout.',    NOW(), NOW(), (SELECT campaign_id FROM campaign WHERE title='Blood Donation Drive'),         (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu')),
(45,  'Distribution pipeline stable.',                  NOW(), NOW(), (SELECT campaign_id FROM campaign WHERE title='Neighborhood Food Bank'),       (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu')),
(60,  'Beach areas A and B done, moving to C.',         NOW(), NOW(), (SELECT campaign_id FROM campaign WHERE title='Coastal Cleanup'),              (SELECT user_id FROM "user" WHERE email='karim.salah@uni.edu')),
(100, 'Hospital visits completed for the quarter.',    NOW(), NOW(), (SELECT campaign_id FROM campaign WHERE title='Hospital Visits Program'),      (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu')),
(100, 'All 500 trees planted.',                         NOW(), NOW(), (SELECT campaign_id FROM campaign WHERE title='Tree Planting Day'),            (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu'));

-- 6) APPLICATIONS (40) — mix of statuses
INSERT INTO application (motivation_letter, status, admin_notes, rejection_reason, applied_at, withdrawn_at, created_at, updated_at, reviewed_at, removal_reason, removed_at, student_id, campaign_id, reviewed_by_id, removed_by_id) VALUES
-- Green Campus Cleanup
('I care about sustainability.',         'APPROVED', 'Strong fit.',            NULL, NOW() - INTERVAL '8 day', NULL, NOW(), NOW(), NOW() - INTERVAL '7 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Green Campus Cleanup'), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu'), NULL),
('I want to lead a team.',               'APPROVED', NULL,                     NULL, NOW() - INTERVAL '7 day', NULL, NOW(), NOW(), NOW() - INTERVAL '6 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='hana.sami@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='Green Campus Cleanup'), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu'), NULL),
('Available weekends.',                  'PENDING',  NULL,                     NULL, NOW() - INTERVAL '2 day', NULL, NOW(), NOW(), NULL, NULL, NULL, (SELECT user_id FROM "user" WHERE email='rana.ehab@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='Green Campus Cleanup'), NULL, NULL),
('I have organizing experience.',        'APPROVED', NULL,                     NULL, NOW() - INTERVAL '5 day', NULL, NOW(), NOW(), NOW() - INTERVAL '4 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='ziad.helmy@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Green Campus Cleanup'), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu'), NULL),
-- Weekend Math Tutoring
('Can teach algebra and geometry.',      'PENDING',  NULL,                     NULL, NOW() - INTERVAL '5 day', NULL, NOW(), NOW(), NULL, NULL, NULL, (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Weekend Math Tutoring'), NULL, NULL),
('Tutoring experience for 2 years.',     'APPROVED', 'Great references.',      NULL, NOW() - INTERVAL '9 day', NULL, NOW(), NOW(), NOW() - INTERVAL '8 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='dina.younis@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='Weekend Math Tutoring'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu'), NULL),
('I love helping young students.',       'APPROVED', NULL,                     NULL, NOW() - INTERVAL '6 day', NULL, NOW(), NOW(), NOW() - INTERVAL '5 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='nada.magdy@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='Weekend Math Tutoring'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu'), NULL),
('Free on Saturdays.',                   'REJECTED', NULL,                     'Capacity reached.', NOW() - INTERVAL '4 day', NULL, NOW(), NOW(), NOW() - INTERVAL '3 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='salma.wagdy@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Weekend Math Tutoring'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu'), NULL),
('Strong in geometry.',                  'WITHDRAWN',NULL,                     NULL, NOW() - INTERVAL '10 day', NOW() - INTERVAL '6 day', NOW(), NOW(), NULL, NULL, NULL, (SELECT user_id FROM "user" WHERE email='fady.naguib@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Weekend Math Tutoring'), NULL, NULL),
-- Blood Donation Drive
('I can coordinate logistics.',          'APPROVED', 'Registration desk.',     NULL, NOW() - INTERVAL '35 day', NULL, NOW(), NOW(), NOW() - INTERVAL '34 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Blood Donation Drive'), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu'), NULL),
('Pre-med background.',                  'APPROVED', NULL,                     NULL, NOW() - INTERVAL '36 day', NULL, NOW(), NOW(), NOW() - INTERVAL '35 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='mai.sherif@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='Blood Donation Drive'), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu'), NULL),
('Want to support patients.',            'APPROVED', NULL,                     NULL, NOW() - INTERVAL '38 day', NULL, NOW(), NOW(), NOW() - INTERVAL '37 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Blood Donation Drive'), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu'), NULL),
-- Neighborhood Food Bank
('Weekend shifts available.',            'REJECTED', NULL,                     'No remaining slots.', NOW() - INTERVAL '3 day', NULL, NOW(), NOW(), NOW() - INTERVAL '2 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Neighborhood Food Bank'), (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu'), NULL),
('Strong logistics background.',         'APPROVED', NULL,                     NULL, NOW() - INTERVAL '6 day', NULL, NOW(), NOW(), NOW() - INTERVAL '5 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='sami.talaat@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Neighborhood Food Bank'), (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu'), NULL),
('Looking to contribute regularly.',     'PENDING',  NULL,                     NULL, NOW() - INTERVAL '1 day', NULL, NOW(), NOW(), NULL, NULL, NULL, (SELECT user_id FROM "user" WHERE email='bassem.kamal@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Neighborhood Food Bank'), NULL, NULL),
-- Senior Digital Literacy
('Patient with teaching seniors.',       'APPROVED', 'Great communication.',   NULL, NOW() - INTERVAL '1 day', NULL, NOW(), NOW(), NOW() - INTERVAL '10 hour', NULL, NULL, (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Senior Digital Literacy'), (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'), NULL),
('Comfortable with tech support.',       'APPROVED', NULL,                     NULL, NOW() - INTERVAL '1 day', NULL, NOW(), NOW(), NOW() - INTERVAL '8 hour', NULL, NULL, (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Senior Digital Literacy'), (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'), NULL),
('I speak the local dialect well.',      'PENDING',  NULL,                     NULL, NOW() - INTERVAL '5 hour', NULL, NOW(), NOW(), NULL, NULL, NULL, (SELECT user_id FROM "user" WHERE email='heba.saad@uni.edu'),     (SELECT campaign_id FROM campaign WHERE title='Senior Digital Literacy'), NULL, NULL),
-- Coastal Cleanup
('Diving certified, can support marine work.', 'APPROVED', NULL,               NULL, NOW() - INTERVAL '5 day', NULL, NOW(), NOW(), NOW() - INTERVAL '4 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='mostafa.gad@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Coastal Cleanup'), (SELECT user_id FROM "user" WHERE email='karim.salah@uni.edu'), NULL),
('Available on weekends.',               'PENDING',  NULL,                     NULL, NOW() - INTERVAL '2 day', NULL, NOW(), NOW(), NULL, NULL, NULL, (SELECT user_id FROM "user" WHERE email='reem.ashraf@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Coastal Cleanup'), NULL, NULL),
('Beach lover and avid recycler.',       'APPROVED', NULL,                     NULL, NOW() - INTERVAL '6 day', NULL, NOW(), NOW(), NOW() - INTERVAL '5 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='hala.anwar@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Coastal Cleanup'), (SELECT user_id FROM "user" WHERE email='karim.salah@uni.edu'), NULL),
-- Children Reading Hour
('Library volunteer history.',           'APPROVED', NULL,                     NULL, NOW() - INTERVAL '2 day', NULL, NOW(), NOW(), NOW() - INTERVAL '1 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='nada.magdy@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='Children Reading Hour'), (SELECT user_id FROM "user" WHERE email='ziad.helmy@uni.edu'), NULL),
('Love working with kids.',              'PENDING',  NULL,                     NULL, NOW() - INTERVAL '1 day', NULL, NOW(), NOW(), NULL, NULL, NULL, (SELECT user_id FROM "user" WHERE email='yara.galal@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='Children Reading Hour'), NULL, NULL),
-- Hospital Visits Program
('Med student, prior hospital exp.',     'APPROVED', NULL,                     NULL, NOW() - INTERVAL '55 day', NULL, NOW(), NOW(), NOW() - INTERVAL '54 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='sara.mansour@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Hospital Visits Program'), (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu'), NULL),
('Comfortable with pediatric wards.',    'APPROVED', NULL,                     NULL, NOW() - INTERVAL '54 day', NULL, NOW(), NOW(), NOW() - INTERVAL '53 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='marwan.fathy@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Hospital Visits Program'), (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu'), NULL),
('Tagged-out by removal.',               'CANCELLED',NULL,                     NULL, NOW() - INTERVAL '50 day', NULL, NOW(), NOW(), NOW() - INTERVAL '48 day', 'Schedule conflict.', NOW() - INTERVAL '40 day', (SELECT user_id FROM "user" WHERE email='hala.anwar@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Hospital Visits Program'), (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu'), (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu')),
-- Animal Shelter Volunteer Day
('Owned dogs my whole life.',            'APPROVED', NULL,                     NULL, NOW() - INTERVAL '2 day', NULL, NOW(), NOW(), NOW() - INTERVAL '1 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='salma.wagdy@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Animal Shelter Volunteer Day'), (SELECT user_id FROM "user" WHERE email='dina.younis@uni.edu'), NULL),
('Comfortable around cats too.',         'PENDING',  NULL,                     NULL, NOW() - INTERVAL '1 day', NULL, NOW(), NOW(), NULL, NULL, NULL, (SELECT user_id FROM "user" WHERE email='habiba.imam@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Animal Shelter Volunteer Day'), NULL, NULL),
('Bio student, love animal welfare.',    'APPROVED', NULL,                     NULL, NOW() - INTERVAL '3 day', NULL, NOW(), NOW(), NOW() - INTERVAL '2 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='reem.ashraf@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Animal Shelter Volunteer Day'), (SELECT user_id FROM "user" WHERE email='dina.younis@uni.edu'), NULL),
-- University Hackathon Helpers (PENDING campaign, application is also PENDING)
('Eng background, organizing experience.', 'PENDING',NULL,                     NULL, NOW() - INTERVAL '6 hour', NULL, NOW(), NOW(), NULL, NULL, NULL, (SELECT user_id FROM "user" WHERE email='noor.fawzy@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='University Hackathon Helpers'), NULL, NULL),
('Will help with logistics.',            'PENDING',  NULL,                     NULL, NOW() - INTERVAL '4 hour', NULL, NOW(), NOW(), NULL, NULL, NULL, (SELECT user_id FROM "user" WHERE email='karim.salah@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='University Hackathon Helpers'), NULL, NULL),
-- Football Coaching Camp
('Played football competitively.',       'PENDING',  NULL,                     NULL, NOW() - INTERVAL '3 day', NULL, NOW(), NOW(), NULL, NULL, NULL, (SELECT user_id FROM "user" WHERE email='tamer.rifaat@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Football Coaching Camp'), NULL, NULL),
('Coaching certification.',              'PENDING',  NULL,                     NULL, NOW() - INTERVAL '2 day', NULL, NOW(), NOW(), NULL, NULL, NULL, (SELECT user_id FROM "user" WHERE email='bassem.kamal@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Football Coaching Camp'), NULL, NULL),
-- Recycling Awareness Booth (REJECTED campaign - older application)
('Eco-club president.',                  'REJECTED', NULL,                     'Campaign not approved.', NOW() - INTERVAL '95 day', NULL, NOW(), NOW(), NOW() - INTERVAL '90 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='noor.fawzy@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Recycling Awareness Booth'), (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'), NULL),
-- Refugee Language Help (REJECTED campaign)
('Bilingual.',                           'REJECTED', NULL,                     'Campaign not approved.', NOW() - INTERVAL '85 day', NULL, NOW(), NOW(), NOW() - INTERVAL '82 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='heba.saad@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Refugee Language Help'), (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'), NULL),
-- Tree Planting Day
('Strong outdoor stamina.',              'APPROVED', NULL,                     NULL, NOW() - INTERVAL '10 day', NULL, NOW(), NOW(), NOW() - INTERVAL '9 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='noor.fawzy@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Tree Planting Day'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu'), NULL),
('Love trees.',                          'APPROVED', NULL,                     NULL, NOW() - INTERVAL '9 day', NULL, NOW(), NOW(), NOW() - INTERVAL '8 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Tree Planting Day'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu'), NULL),
('Available all day.',                   'APPROVED', NULL,                     NULL, NOW() - INTERVAL '8 day', NULL, NOW(), NOW(), NOW() - INTERVAL '7 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='fady.naguib@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Tree Planting Day'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu'), NULL),
('Bringing 5 friends.',                  'APPROVED', NULL,                     NULL, NOW() - INTERVAL '7 day', NULL, NOW(), NOW(), NOW() - INTERVAL '6 day', NULL, NULL, (SELECT user_id FROM "user" WHERE email='yara.galal@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Tree Planting Day'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu'), NULL),
-- Music for Kids (CANCELED campaign)
('Play guitar and piano.',               'CANCELLED', NULL,                    NULL, NOW() - INTERVAL '10 day', NOW() - INTERVAL '5 day', NOW(), NOW(), NULL, NULL, NULL, (SELECT user_id FROM "user" WHERE email='ziad.helmy@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Music for Kids'), NULL, NULL);

-- 7) ATTENDANCE (80 records across campaigns)
INSERT INTO attendance (attendance_date, status, hours_that_day, notes, recorded_at, created_at, updated_at, student_id, campaign_id, recorded_by_id) VALUES
-- Green Campus Cleanup
(CURRENT_DATE - 9, 'PRESENT', 4.0, 'Sorting waste.',       NOW() - INTERVAL '9 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Green Campus Cleanup'), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu')),
(CURRENT_DATE - 8, 'PRESENT', 3.5, 'Managed point B.',     NOW() - INTERVAL '8 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Green Campus Cleanup'), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu')),
(CURRENT_DATE - 7, 'ABSENT',  0.0, 'No show.',             NOW() - INTERVAL '7 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Green Campus Cleanup'), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu')),
(CURRENT_DATE - 6, 'PRESENT', 4.0, 'Recycling drive.',     NOW() - INTERVAL '6 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='hana.sami@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Green Campus Cleanup'), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu')),
(CURRENT_DATE - 5, 'PRESENT', 3.0, 'Setup recycling bins.',NOW() - INTERVAL '5 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='hana.sami@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Green Campus Cleanup'), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu')),
(CURRENT_DATE - 4, 'PRESENT', 2.5, 'Cleanup zone 4.',      NOW() - INTERVAL '4 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='ziad.helmy@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Green Campus Cleanup'), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu')),
(CURRENT_DATE - 3, 'EXCUSED', 0.0, 'Medical leave.',       NOW() - INTERVAL '3 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='ziad.helmy@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Green Campus Cleanup'), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu')),
(CURRENT_DATE - 2, 'PRESENT', 3.5, 'Cleanup zone 5.',      NOW() - INTERVAL '2 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='ziad.helmy@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Green Campus Cleanup'), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu')),
-- Weekend Math Tutoring
(CURRENT_DATE - 12, 'PRESENT', 2.5, 'Algebra session 1.',   NOW() - INTERVAL '12 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Weekend Math Tutoring'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu')),
(CURRENT_DATE - 6,  'EXCUSED', 0.0, 'Medical.',             NOW() - INTERVAL '6 day',  NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Weekend Math Tutoring'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu')),
(CURRENT_DATE - 5,  'PRESENT', 3.0, 'Geometry session.',    NOW() - INTERVAL '5 day',  NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Weekend Math Tutoring'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu')),
(CURRENT_DATE - 12, 'PRESENT', 2.0, 'Helped grade 8.',      NOW() - INTERVAL '12 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='dina.younis@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Weekend Math Tutoring'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu')),
(CURRENT_DATE - 5,  'PRESENT', 2.5, 'Helped grade 9.',      NOW() - INTERVAL '5 day',  NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='dina.younis@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Weekend Math Tutoring'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu')),
(CURRENT_DATE - 4,  'PRESENT', 3.0, 'Helped grade 10.',     NOW() - INTERVAL '4 day',  NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='nada.magdy@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Weekend Math Tutoring'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu')),
(CURRENT_DATE - 3,  'ABSENT',  0.0, 'No notice.',           NOW() - INTERVAL '3 day',  NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='nada.magdy@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Weekend Math Tutoring'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu')),
(CURRENT_DATE - 2,  'PRESENT', 2.0, 'Make-up session.',     NOW() - INTERVAL '2 day',  NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='nada.magdy@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Weekend Math Tutoring'), (SELECT user_id FROM "user" WHERE email='mariam.adel@uni.edu')),
-- Blood Donation Drive (15 records)
(CURRENT_DATE - 38, 'PRESENT', 5.0, 'Donor check-in.',        NOW() - INTERVAL '38 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Blood Donation Drive'), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu')),
(CURRENT_DATE - 37, 'PRESENT', 4.5, 'Donor support.',         NOW() - INTERVAL '37 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Blood Donation Drive'), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu')),
(CURRENT_DATE - 36, 'PRESENT', 5.0, 'Helped 30 donors.',      NOW() - INTERVAL '36 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Blood Donation Drive'), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu')),
(CURRENT_DATE - 35, 'ABSENT',  0.0, 'Sick.',                  NOW() - INTERVAL '35 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='yousef.nabil@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Blood Donation Drive'), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu')),
(CURRENT_DATE - 38, 'PRESENT', 6.0, 'Helped medical team.',   NOW() - INTERVAL '38 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='mai.sherif@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='Blood Donation Drive'), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu')),
(CURRENT_DATE - 37, 'PRESENT', 5.5, 'Pre-screening duty.',    NOW() - INTERVAL '37 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='mai.sherif@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='Blood Donation Drive'), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu')),
(CURRENT_DATE - 36, 'PRESENT', 6.0, 'Post-donation care.',    NOW() - INTERVAL '36 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='mai.sherif@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='Blood Donation Drive'), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu')),
(CURRENT_DATE - 35, 'PRESENT', 5.5, 'Lab transport.',         NOW() - INTERVAL '35 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Blood Donation Drive'), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu')),
(CURRENT_DATE - 34, 'PRESENT', 6.0, 'Logistics lead.',        NOW() - INTERVAL '34 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Blood Donation Drive'), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu')),
(CURRENT_DATE - 33, 'PRESENT', 5.0, 'Closing duties.',        NOW() - INTERVAL '33 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Blood Donation Drive'), (SELECT user_id FROM "user" WHERE email='aisha.rahman@uni.edu')),
-- Neighborhood Food Bank
(CURRENT_DATE - 6, 'PRESENT', 3.0, 'Packed 40 boxes.',   NOW() - INTERVAL '6 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Neighborhood Food Bank'), (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu')),
(CURRENT_DATE - 5, 'ABSENT',  0.0, 'No show.',           NOW() - INTERVAL '5 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Neighborhood Food Bank'), (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu')),
(CURRENT_DATE - 4, 'PRESENT', 3.5, 'Helped delivery.',   NOW() - INTERVAL '4 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Neighborhood Food Bank'), (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu')),
(CURRENT_DATE - 6, 'PRESENT', 4.0, 'Drove truck.',       NOW() - INTERVAL '6 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='sami.talaat@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Neighborhood Food Bank'), (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu')),
(CURRENT_DATE - 5, 'PRESENT', 3.5, 'Packed food parcels.',NOW() - INTERVAL '5 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='sami.talaat@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Neighborhood Food Bank'), (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu')),
(CURRENT_DATE - 4, 'PRESENT', 4.0, 'Box distribution.',  NOW() - INTERVAL '4 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='sami.talaat@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Neighborhood Food Bank'), (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu')),
-- Senior Digital Literacy (preparation attendance)
(CURRENT_DATE, 'PRESENT', 2.0, 'Workshop handouts.',     NOW(), NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='lina.khaled@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Senior Digital Literacy'), (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu')),
(CURRENT_DATE, 'PRESENT', 1.5, 'Tested lab laptops.',    NOW(), NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Senior Digital Literacy'), (SELECT user_id FROM "user" WHERE email='omar.hassan@uni.edu')),
-- Coastal Cleanup
(CURRENT_DATE - 2, 'PRESENT', 4.0, 'Beach zone A.',      NOW() - INTERVAL '2 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='mostafa.gad@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Coastal Cleanup'), (SELECT user_id FROM "user" WHERE email='karim.salah@uni.edu')),
(CURRENT_DATE - 1, 'PRESENT', 4.5, 'Beach zone B.',      NOW() - INTERVAL '1 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='mostafa.gad@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Coastal Cleanup'), (SELECT user_id FROM "user" WHERE email='karim.salah@uni.edu')),
(CURRENT_DATE - 2, 'PRESENT', 3.5, 'Coral monitoring.',  NOW() - INTERVAL '2 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='hala.anwar@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='Coastal Cleanup'), (SELECT user_id FROM "user" WHERE email='karim.salah@uni.edu')),
(CURRENT_DATE - 1, 'ABSENT',  0.0, 'Travel delay.',      NOW() - INTERVAL '1 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='hala.anwar@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='Coastal Cleanup'), (SELECT user_id FROM "user" WHERE email='karim.salah@uni.edu')),
-- Hospital Visits Program (already completed)
(CURRENT_DATE - 50, 'PRESENT', 3.0, 'Ward A visits.',     NOW() - INTERVAL '50 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='sara.mansour@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Hospital Visits Program'), (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu')),
(CURRENT_DATE - 48, 'PRESENT', 3.5, 'Ward B visits.',     NOW() - INTERVAL '48 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='sara.mansour@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Hospital Visits Program'), (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu')),
(CURRENT_DATE - 45, 'EXCUSED', 0.0, 'Exam day.',          NOW() - INTERVAL '45 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='sara.mansour@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Hospital Visits Program'), (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu')),
(CURRENT_DATE - 42, 'PRESENT', 4.0, 'Games and crafts.',  NOW() - INTERVAL '42 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='sara.mansour@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Hospital Visits Program'), (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu')),
(CURRENT_DATE - 50, 'PRESENT', 3.0, 'Pediatric ward.',    NOW() - INTERVAL '50 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='marwan.fathy@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Hospital Visits Program'), (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu')),
(CURRENT_DATE - 48, 'PRESENT', 3.5, 'Reading sessions.',  NOW() - INTERVAL '48 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='marwan.fathy@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Hospital Visits Program'), (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu')),
(CURRENT_DATE - 45, 'PRESENT', 4.0, 'Outdoor garden time.', NOW() - INTERVAL '45 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='marwan.fathy@uni.edu'), (SELECT campaign_id FROM campaign WHERE title='Hospital Visits Program'), (SELECT user_id FROM "user" WHERE email='ahmed.lotfy@uni.edu')),
-- Tree Planting Day
(CURRENT_DATE - 5, 'PRESENT', 6.0, 'Planted 80 trees.',   NOW() - INTERVAL '5 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='noor.fawzy@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='Tree Planting Day'), (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu')),
(CURRENT_DATE - 4, 'PRESENT', 6.5, 'Planted 90 trees.',   NOW() - INTERVAL '4 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='noor.fawzy@uni.edu'),    (SELECT campaign_id FROM campaign WHERE title='Tree Planting Day'), (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu')),
(CURRENT_DATE - 5, 'PRESENT', 6.0, 'Planted 75 trees.',   NOW() - INTERVAL '5 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Tree Planting Day'), (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu')),
(CURRENT_DATE - 4, 'PRESENT', 6.0, 'Planted 70 trees.',   NOW() - INTERVAL '4 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Tree Planting Day'), (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu')),
(CURRENT_DATE - 5, 'PRESENT', 5.5, 'Planted 65 trees.',   NOW() - INTERVAL '5 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='fady.naguib@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Tree Planting Day'), (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu')),
(CURRENT_DATE - 4, 'ABSENT',  0.0, 'Family emergency.',   NOW() - INTERVAL '4 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='fady.naguib@uni.edu'),  (SELECT campaign_id FROM campaign WHERE title='Tree Planting Day'), (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu')),
(CURRENT_DATE - 5, 'PRESENT', 5.0, 'Planted 60 trees.',   NOW() - INTERVAL '5 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='yara.galal@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Tree Planting Day'), (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu')),
(CURRENT_DATE - 4, 'PRESENT', 5.5, 'Watering.',           NOW() - INTERVAL '4 day', NOW(), NOW(), (SELECT user_id FROM "user" WHERE email='yara.galal@uni.edu'),   (SELECT campaign_id FROM campaign WHERE title='Tree Planting Day'), (SELECT user_id FROM "user" WHERE email='hussein.ali@uni.edu'));

COMMIT;

-- Verify
SELECT 'colleges' AS table_name, COUNT(*) AS rows FROM college
UNION ALL SELECT 'categories', COUNT(*) FROM category
UNION ALL SELECT 'users',      COUNT(*) FROM "user"
UNION ALL SELECT 'campaigns',  COUNT(*) FROM campaign
UNION ALL SELECT 'progress',   COUNT(*) FROM progress
UNION ALL SELECT 'applications', COUNT(*) FROM application
UNION ALL SELECT 'attendance', COUNT(*) FROM attendance;
